#!/bin/bash

if [[ x$1 = x ]]
then
   echo "Please specify a L4T version"
   exit
fi

if [[ x$2 = x ]]
then
   echo "Please specify a board"
   exit
fi

LINUX_FOR_TEGRA_DIR=Linux_for_Tegra_${2}
L4T_VERSION=$1
L4T_VERSION_EXTENDED=${L4T_VERSION}_${2}
ROOT_DIR=$(pwd)
ARCHIVE_DIR=$ROOT_DIR/archives
. /usr/lib/git-core/git-sh-prompt
GIT_TAG=$(echo $(__git_ps1) | sed 's/[()]//g')
GIT_COMMIT=$(git rev-parse --short HEAD)

JETSON_DIR=$ROOT_DIR/$L4T_VERSION
if [[ -d $JETSON_DIR/${LINUX_FOR_TEGRA_DIR}/source/public ]]
then
   L4T_SRC=$JETSON_DIR/${LINUX_FOR_TEGRA_DIR}/source/public
else
   L4T_SRC=$JETSON_DIR/${LINUX_FOR_TEGRA_DIR}/source
fi

case "${1}" in
32.7.1)
   case "${2}" in
   nano)
      JETSON_PUBLIC_SOURCES=public_sources.tbz2
      JETSON_PUBLIC_SOURCES_URL=https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.1/sources/t210/${JETSON_PUBLIC_SOURCES}
      JETSON_TOOCHAIN_ARCHIVE=gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
      JETSON_TOOCHAIN_ARCHIVE_URL=https://developer.nvidia.com/embedded/dlc/l4t-gcc-7-3-1-toolchain-64-bit
      TOOLCHAIN_DIR=l4t-gcc
      TOOLCHAIN_PREFIX=$JETSON_DIR/$TOOLCHAIN_DIR/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
      L4T_RELEASE_PACKAGE=jetson-210_linux_r32.7.1_aarch64.tbz2
      L4T_RELEASE_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.1/t210/${L4T_RELEASE_PACKAGE}
      SAMPLE_FS_PACKAGE=tegra_linux_sample-root-filesystem_r32.7.1_aarch64.tbz2
      SAMPLE_FS_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.1/t210/${SAMPLE_FS_PACKAGE}
      ;;
   *)
      echo "Incorrect board. $1 is compatible with nan"
      exit
      ;;
   esac
   ;;

32.7.4)
   case "${2}" in
   nano)
      JETSON_PUBLIC_SOURCES=public_sources.tbz2
      JETSON_PUBLIC_SOURCES_URL=https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.4/sources/t210/${JETSON_PUBLIC_SOURCES}
      JETSON_TOOCHAIN_ARCHIVE=gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu.tar.xz
      JETSON_TOOCHAIN_ARCHIVE_URL=https://developer.nvidia.com/embedded/dlc/l4t-gcc-7-3-1-toolchain-64-bit
      TOOLCHAIN_DIR=l4t-gcc
      TOOLCHAIN_PREFIX=$JETSON_DIR/$TOOLCHAIN_DIR/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-
      L4T_RELEASE_PACKAGE=jetson-210_linux_r32.7.4_aarch64.tbz2
      L4T_RELEASE_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.4/t210/${L4T_RELEASE_PACKAGE}
      SAMPLE_FS_PACKAGE=tegra_linux_sample-root-filesystem_r32.7.4_aarch64.tbz2
      SAMPLE_FS_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r32_release_v7.4/t210/${SAMPLE_FS_PACKAGE}
      ;;
   *)
      echo "Incorrect board. $1 is compatible with nano"
      exit
      ;;
   esac
   ;;

35.1)
   case "${2}" in
   generic|xavier_nx)
      JETSON_PUBLIC_SOURCES=public_sources.tbz2
      JETSON_PUBLIC_SOURCES_URL=https://developer.nvidia.com/embedded/l4t/r35_release_v1.0/sources/${JETSON_PUBLIC_SOURCES}
      JETSON_TOOCHAIN_ARCHIVE=aarch64--glibc--stable-final.tar.gz
      JETSON_TOOCHAIN_ARCHIVE_URL=https://developer.nvidia.com/embedded/jetson-linux/bootlin-toolchain-gcc-93
      TOOLCHAIN_DIR=l4t-gcc
      TOOLCHAIN_PREFIX=$JETSON_DIR/$TOOLCHAIN_DIR/bin/aarch64-buildroot-linux-gnu-
      L4T_RELEASE_PACKAGE=jetson_linux_r35.1.0_aarch64.tbz2
      L4T_RELEASE_PACKAGE_URL=https://developer.nvidia.com/embedded/l4t/r35_release_v1.0/release/${L4T_RELEASE_PACKAGE}
      SAMPLE_FS_PACKAGE=tegra_linux_sample-root-filesystem_r35.1.0_aarch64.tbz2
      SAMPLE_FS_PACKAGE_URL=https://developer.nvidia.com/embedded/l4t/r35_release_v1.0/release/${SAMPLE_FS_PACKAGE}
      ;;
   *)
      echo "Incorrect board. $1 is compatible with xavier_nx"
      exit
      ;;
   esac
   ;;

35.3.1)
   case "${2}" in
   generic|xavier_nx|agx_orin_auvidea_X230D)
      JETSON_PUBLIC_SOURCES=public_sources.tbz2
      JETSON_PUBLIC_SOURCES_URL=https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v3.1/sources/${JETSON_PUBLIC_SOURCES}
      JETSON_TOOCHAIN_ARCHIVE=aarch64--glibc--stable-final.tar.gz
      JETSON_TOOCHAIN_ARCHIVE_URL=https://developer.nvidia.com/embedded/jetson-linux/bootlin-toolchain-gcc-93
      TOOLCHAIN_DIR=l4t-gcc
      TOOLCHAIN_PREFIX=$JETSON_DIR/$TOOLCHAIN_DIR/bin/aarch64-buildroot-linux-gnu-
      L4T_RELEASE_PACKAGE=jetson_linux_r35.3.1_aarch64.tbz2
      L4T_RELEASE_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v3.1/release/${L4T_RELEASE_PACKAGE}
      SAMPLE_FS_PACKAGE=tegra_linux_sample-root-filesystem_r35.3.1_aarch64.tbz2
      SAMPLE_FS_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v3.1/release/${SAMPLE_FS_PACKAGE}
      ;;
   *)
      echo "Incorrect board. $1 is compatible with xavier_nx or agx_orin_auvidea_X230D"
      exit
      ;;
   esac
   ;;

35.4.1)
   case "${2}" in
   generic|xavier_nx|agx_orin_auvidea_X230D)
      JETSON_PUBLIC_SOURCES=public_sources.tbz2
      JETSON_PUBLIC_SOURCES_URL=https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v4.1/sources/${JETSON_PUBLIC_SOURCES}
      JETSON_TOOCHAIN_ARCHIVE=aarch64--glibc--stable-final.tar.gz
      JETSON_TOOCHAIN_ARCHIVE_URL=https://developer.nvidia.com/embedded/jetson-linux/bootlin-toolchain-gcc-93
      TOOLCHAIN_DIR=l4t-gcc
      TOOLCHAIN_PREFIX=$JETSON_DIR/$TOOLCHAIN_DIR/bin/aarch64-buildroot-linux-gnu-
      L4T_RELEASE_PACKAGE=jetson_linux_r35.4.1_aarch64.tbz2
      L4T_RELEASE_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v4.1/release/${L4T_RELEASE_PACKAGE}
      SAMPLE_FS_PACKAGE=tegra_linux_sample-root-filesystem_r35.4.1_aarch64.tbz2
      SAMPLE_FS_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v4.1/release/${SAMPLE_FS_PACKAGE}
      ;;
   *)
      echo "Incorrect board. $1 is compatible with xavier_nx or agx_orin_auvidea_X230D"
      exit
      ;;
   esac
   ;;

35.5.0)
   case "${2}" in
   generic|xavier_nx|agx_orin_auvidea_X230D)
      JETSON_PUBLIC_SOURCES=public_sources.tbz2
      JETSON_PUBLIC_SOURCES_URL=https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v5.0/sources/${JETSON_PUBLIC_SOURCES}
      JETSON_TOOCHAIN_ARCHIVE=aarch64--glibc--stable-final.tar.gz
      JETSON_TOOCHAIN_ARCHIVE_URL=https://developer.nvidia.com/embedded/jetson-linux/bootlin-toolchain-gcc-93
      TOOLCHAIN_DIR=l4t-gcc
      TOOLCHAIN_PREFIX=$JETSON_DIR/$TOOLCHAIN_DIR/bin/aarch64-buildroot-linux-gnu-
      L4T_RELEASE_PACKAGE=jetson_linux_r35.5.0_aarch64.tbz2
      L4T_RELEASE_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v5.0/release/${L4T_RELEASE_PACKAGE}
      SAMPLE_FS_PACKAGE=tegra_linux_sample-root-filesystem_r35.5.0_aarch64.tbz2
      SAMPLE_FS_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r35_release_v5.0/release/${SAMPLE_FS_PACKAGE}
      ;;
   *)
      echo "Incorrect board. $1 is compatible with xavier_nx or agx_orin_auvidea_X230D"
      exit
      ;;
   esac
   ;;

#36.3)
#   case "${2}" in
#   generic|agx_orin_auvidea_X230D|orin_nx)
#      JETSON_PUBLIC_SOURCES=public_sources.tbz2
#      JETSON_PUBLIC_SOURCES_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v3.0/sources/${JETSON_PUBLIC_SOURCES}
#      JETSON_TOOCHAIN_ARCHIVE=aarch64--glibc--stable-2022.08-1.tar.bz2
#      JETSON_TOOCHAIN_ARCHIVE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v3.0/toolchain/$JETSON_TOOCHAIN_ARCHIVE
#      TOOLCHAIN_DIR=aarch64--glibc--stable-2022.08-1
#      TOOLCHAIN_PREFIX=$JETSON_DIR/$TOOLCHAIN_DIR/bin/aarch64-buildroot-linux-gnu-
#      L4T_RELEASE_PACKAGE=jetson_linux_r36.3.0_aarch64.tbz2
#      L4T_RELEASE_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v3.0/release/${L4T_RELEASE_PACKAGE}
#      SAMPLE_FS_PACKAGE=tegra_linux_sample-root-filesystem_r36.3.0_aarch64.tbz2
#      SAMPLE_FS_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v3.0/release/${SAMPLE_FS_PACKAGE}
#      ;;
#   *)
#      echo "Incorrect board. $1 is compatible with agx_orin_auvidea_X230D and Orin NX"
#      exit
#      ;;
#   esac
#   ;;

#36.4)
#   case "${2}" in
#   generic|agx_orin_auvidea_X230D|orin_nx)
#      JETSON_PUBLIC_SOURCES=public_sources.tbz2
#      JETSON_PUBLIC_SOURCES_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v4.0/sources/${JETSON_PUBLIC_SOURCES}
#      JETSON_TOOCHAIN_ARCHIVE=aarch64--glibc--stable-2022.08-1.tar.bz2
#      JETSON_TOOCHAIN_ARCHIVE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v3.0/toolchain/$JETSON_TOOCHAIN_ARCHIVE
#      TOOLCHAIN_DIR=aarch64--glibc--stable-2022.08-1
#      TOOLCHAIN_PREFIX=$JETSON_DIR/$TOOLCHAIN_DIR/$TOOLCHAIN_DIR/bin/aarch64-buildroot-linux-gnu-
#      L4T_RELEASE_PACKAGE=jetson_linux_r36.4.0_aarch64.tbz2
#      L4T_RELEASE_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v4.0/release/${L4T_RELEASE_PACKAGE}
#      SAMPLE_FS_PACKAGE=tegra_linux_sample-root-filesystem_r36.4.0_aarch64.tbz2
#      SAMPLE_FS_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v4.0/release/${SAMPLE_FS_PACKAGE}
#      ;;
#   *)
#      echo "Incorrect board. $1 is compatible with agx_orin_auvidea_X230D and Orin NX"
#      exit
#      ;;
#   esac
#   ;;

36.4.3)
   case "${2}" in
   generic|agx_orin_auvidea_X230D|orin_nx)
      JETSON_PUBLIC_SOURCES=public_sources.tbz2
      JETSON_PUBLIC_SOURCES_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v4.3/sources/${JETSON_PUBLIC_SOURCES}
      JETSON_TOOCHAIN_ARCHIVE=aarch64--glibc--stable-2022.08-1.tar.bz2
      JETSON_TOOCHAIN_ARCHIVE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v3.0/toolchain/$JETSON_TOOCHAIN_ARCHIVE
      TOOLCHAIN_DIR=aarch64--glibc--stable-2022.08-1
      TOOLCHAIN_PREFIX=$JETSON_DIR/$TOOLCHAIN_DIR/$TOOLCHAIN_DIR/bin/aarch64-buildroot-linux-gnu-
      L4T_RELEASE_PACKAGE=jetson_linux_r36.4.3_aarch64.tbz2
      L4T_RELEASE_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v4.3/release/${L4T_RELEASE_PACKAGE}
      SAMPLE_FS_PACKAGE=tegra_linux_sample-root-filesystem_r36.4.3_aarch64.tbz2
      SAMPLE_FS_PACKAGE_URL=https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v4.3/release/${SAMPLE_FS_PACKAGE}
      ;;
   *)
      echo "Incorrect board. $1 is compatible with agx_orin_auvidea_X230D and Orin NX"
      exit
      ;;
   esac
   ;;

*)
   echo "Incorrect version. Versions 32.7.1, 32.7.4, 35.1, 35.3.1, 35.4.1, 35.5.0, 36.4.3 are supported"
   exit
   ;;
esac

