#!/bin/bash
#******************************************************************************
# l4t_verify_packages.sh - Verify Debian packages generated by l4t_gen_delivery_package.sh
#
# Usage:
#   ./l4t_verify_packages.sh [-v <version>] [-V <vendor>] [-s <som>] [-c <carrier-board>] [--verbose]
#
# This script verifies that the installation directory used for Debian package
# generation contains all expected files.
#
# Options:
#   -v, --l4t-version VERSION   Version filter (supports wildcards: 36.*, 35.6.*)
#   -V, --vendor VENDOR         Vendor filter: generic, forecr (default: all)
#   -s, --som SOM               SoM filter: t210, t186 (32.x only, default: all)
#   -c, --carrier-board BOARD   Carrier board filter (default: all for vendor)
#   --verbose                   Show detailed file paths
#   --list                      List matching configurations and exit
#   -h, --help                  Show this help message
#
# Examples:
#   ./l4t_verify_packages.sh                        # Verify all packages
#   ./l4t_verify_packages.sh -v 36.4.3              # Verify 36.4.3 all vendors
#   ./l4t_verify_packages.sh -v 36.4.3 -V forecr    # Verify 36.4.3 forecr only
#   ./l4t_verify_packages.sh -v 32.7.1 -s t186      # Verify 32.7.1 t186 SoM
#   ./l4t_verify_packages.sh -v "36.*" --verbose    # Verify all 36.x with details
#******************************************************************************

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source unified environment (provides enumeration functions)
. "$SCRIPT_DIR/l4t_environment.sh"

#******************************************************************************
# Default values
#******************************************************************************
VERSION_FILTER=""
VENDOR_FILTER=""
SOM_FILTER=""
CARRIER_FILTER=""
VERBOSE=0
LIST_ONLY=0

#******************************************************************************
# Colors
#******************************************************************************
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

#******************************************************************************
# Help function
#******************************************************************************
show_help() {
    head -24 "$0" | tail -n +2 | sed 's/^#//' | sed 's/^\*//g'
    echo ""
    local all_versions=$(get_all_versions)
    echo "Available versions: $all_versions"
    echo ""
    echo "Version-vendor support:"
    for v in $all_versions; do
        local vendors=$(get_vendors_for_version "$v")
        echo "  $v: $vendors"
    done
}

#******************************************************************************
# Parse arguments
#******************************************************************************
while [[ $# -gt 0 ]]; do
    case "$1" in
        -v|--l4t-version)
            VERSION_FILTER="$2"
            shift 2
            ;;
        -V|--vendor)
            VENDOR_FILTER="$2"
            shift 2
            ;;
        -s|--som)
            SOM_FILTER="$2"
            shift 2
            ;;
        -c|--carrier-board)
            CARRIER_FILTER="$2"
            shift 2
            ;;
        --verbose)
            VERBOSE=1
            shift
            ;;
        --list)
            LIST_ONLY=1
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo "Error: Unknown argument: $1"
            echo "Use --help for usage information."
            exit 1
            ;;
    esac
done

#******************************************************************************
# Validate filters
#******************************************************************************
if ! validate_filters "$VERSION_FILTER" "$VENDOR_FILTER" "$SOM_FILTER" "$CARRIER_FILTER"; then
    exit 1
fi

#******************************************************************************
# Get configurations to process
#******************************************************************************
configs=$(enumerate_configs "$VERSION_FILTER" "$VENDOR_FILTER" "$SOM_FILTER" "$CARRIER_FILTER")
config_count=$(echo "$configs" | wc -l)

#******************************************************************************
# List mode
#******************************************************************************
if [[ $LIST_ONLY -eq 1 ]]; then
    echo "Matching configurations ($config_count):"
    echo ""
    printf "%-12s %-12s %-8s %-15s\n" "VERSION" "VENDOR" "SOM" "CARRIER"
    echo "-------------------------------------------------------"
    for config in $configs; do
        parse_config "$config"
        printf "%-12s %-12s %-8s %-15s\n" "$CFG_VERSION" "$CFG_VENDOR" "${CFG_SOM:--}" "$CFG_CARRIER"
    done
    exit 0
fi

#******************************************************************************
# Counters
#******************************************************************************
TOTAL_ERRORS=0
TOTAL_WARNINGS=0
TOTAL_CHECKS=0
TOTAL_PASSED=0
TOTAL_FAILED=0
TOTAL_SKIPPED=0

#******************************************************************************
# Helper functions
#******************************************************************************
# Reset per-package counters
reset_counters() {
    PKG_ERRORS=0
    PKG_WARNINGS=0
    PKG_CHECKS=0
}

# Extract expected EG DTBO files from Makefiles
# Args: version, vendor_source_dir (empty for generic)
# Returns: list of expected dtbo filenames (one per line)
get_expected_eg_dtbo() {
    local version="$1"
    local vendor_source_dir="$2"

    local source_base="$SCRIPT_DIR/sources/$version"
    local makefiles=""

    # Determine which source directory to use
    if [[ -n "$vendor_source_dir" ]]; then
        source_base="$source_base/$vendor_source_dir"
    else
        source_base="$source_base/Linux_for_Tegra"
    fi

    # Find all Makefiles containing dtbo-y and eg patterns
    if [[ -d "$source_base" ]]; then
        makefiles=$(find "$source_base" -name "Makefile" -type f -exec grep -l "dtbo.*eg" {} \; 2>/dev/null)
    fi

    # Extract dtbo-y lines containing -eg- patterns
    for makefile in $makefiles; do
        grep -E 'dtbo-.*\+=' "$makefile" 2>/dev/null | \
            grep -E '\-eg\-' | \
            sed -E 's/.*\+= *([^ ]+\.dtbo).*/\1/' | \
            sort -u
    done | sort -u
}

check_file() {
    local file="$1"
    local description="$2"
    local required="${3:-1}"  # 1=required, 0=optional

    PKG_CHECKS=$((PKG_CHECKS + 1))

    if [[ -f "$file" ]]; then
        if [[ $VERBOSE -eq 1 ]]; then
            echo -e "  ${GREEN}[OK]${NC} $description"
            echo "       $file"
        fi
        return 0
    else
        if [[ $required -eq 1 ]]; then
            echo -e "  ${RED}[MISSING]${NC} $description"
            if [[ $VERBOSE -eq 1 ]]; then
                echo "       Expected: $file"
            fi
            PKG_ERRORS=$((PKG_ERRORS + 1))
        else
            if [[ $VERBOSE -eq 1 ]]; then
                echo -e "  ${YELLOW}[OPTIONAL]${NC} $description (not found)"
            fi
            PKG_WARNINGS=$((PKG_WARNINGS + 1))
        fi
        return 1
    fi
}

check_dir() {
    local dir="$1"
    local description="$2"
    local required="${3:-1}"

    PKG_CHECKS=$((PKG_CHECKS + 1))

    if [[ -d "$dir" ]]; then
        if [[ $VERBOSE -eq 1 ]]; then
            local count=$(find "$dir" -type f 2>/dev/null | wc -l)
            echo -e "  ${GREEN}[OK]${NC} $description ($count files)"
            echo "       $dir"
        fi
        return 0
    else
        if [[ $required -eq 1 ]]; then
            echo -e "  ${RED}[MISSING]${NC} $description"
            if [[ $VERBOSE -eq 1 ]]; then
                echo "       Expected: $dir"
            fi
            PKG_ERRORS=$((PKG_ERRORS + 1))
        else
            if [[ $VERBOSE -eq 1 ]]; then
                echo -e "  ${YELLOW}[OPTIONAL]${NC} $description (not found)"
            fi
            PKG_WARNINGS=$((PKG_WARNINGS + 1))
        fi
        return 1
    fi
}

check_files_exist() {
    local dir="$1"
    local pattern="$2"
    local description="$3"
    local required="${4:-1}"

    PKG_CHECKS=$((PKG_CHECKS + 1))

    local files=$(find "$dir" -name "$pattern" -type f 2>/dev/null)
    local count=0
    if [[ -n "$files" ]]; then
        count=$(echo "$files" | wc -l)
    fi

    if [[ $count -gt 0 ]]; then
        if [[ $VERBOSE -eq 1 ]]; then
            echo -e "  ${GREEN}[OK]${NC} $description ($count files matching '$pattern')"
            echo "$files" | head -5 | sed 's/^/       /'
            if [[ $count -gt 5 ]]; then
                echo "       ... and $((count - 5)) more"
            fi
        fi
        return 0
    else
        if [[ $required -eq 1 ]]; then
            echo -e "  ${RED}[MISSING]${NC} $description (no files matching '$pattern')"
            PKG_ERRORS=$((PKG_ERRORS + 1))
        else
            if [[ $VERBOSE -eq 1 ]]; then
                echo -e "  ${YELLOW}[OPTIONAL]${NC} $description (no files matching '$pattern')"
            fi
            PKG_WARNINGS=$((PKG_WARNINGS + 1))
        fi
        return 1
    fi
}

# NOTE: get_eg_modules_from_patch() was replaced by source-based detection above.
# EG modules are now derived from sources/*/Linux_for_Tegra Makefiles, not from patch files.
# get_eg_modules_from_patch() {
#     local version="$1"
#     local vendor="$2"
#     local carrier="${3:-}"
#     local version_major=$(echo "$version" | awk -F '.' '{print $1}')
#     local version_extended="$version"
#     if [[ "$vendor" != "generic" ]]; then
#         version_extended="${version}_${vendor}"
#     fi
#     local patch_file
#     if [[ $version_major -ge 36 ]]; then
#         patch_file="$SCRIPT_DIR/patches/${version_extended}/source_nvidia-oot_drivers_media_i2c.patch"
#     else
#         patch_file="$SCRIPT_DIR/patches/${version_extended}/source_public_kernel_nvidia_drivers_media_i2c.patch"
#     fi
#     if [[ ! -f "$patch_file" ]]; then
#         return
#     fi
#     if [[ $version_major -ge 36 ]]; then
#         grep '^+obj-' "$patch_file" | sed 's/.*+=//' | tr -d '[:blank:]' | sed 's/\.o$//' | sort -u
#         return
#     fi
#     local config_module_pairs
#     config_module_pairs=$(grep '^+obj-' "$patch_file" | \
#         sed -E 's/^\+obj-\$\(([^)]+)\)[[:space:]]*\+=[[:space:]]*/\1 /' | \
#         sed -E 's/\.o[[:space:]]*$//')
#     if [[ -z "$config_module_pairs" ]]; then
#         return
#     fi
#     local defconfig_file=""
#     if [[ -n "$carrier" ]]; then
#         local defconfig_name=$(get_carrier_defconfig "$carrier")
#         if [[ -n "$defconfig_name" ]]; then
#             local carrier_suffix=$(get_carrier_dir_suffix "$carrier")
#             local lft_dir
#             if [[ "$vendor" == "generic" ]]; then
#                 lft_dir="Linux_for_Tegra"
#             elif [[ -n "$carrier_suffix" ]]; then
#                 lft_dir="Linux_for_Tegra_${vendor}_${carrier_suffix}"
#             else
#                 lft_dir="Linux_for_Tegra_${vendor}"
#             fi
#             defconfig_file=$(ls "$SCRIPT_DIR/$version/$lft_dir"/source/public/kernel/kernel-*/arch/arm64/configs/"$defconfig_name" 2>/dev/null | head -1)
#         fi
#     fi
#     while IFS=' ' read -r config_var mod_name; do
#         [[ -z "$mod_name" ]] && continue
#         if [[ -n "$defconfig_file" ]]; then
#             local config_val=$(grep "^${config_var}=" "$defconfig_file" 2>/dev/null | head -1)
#             if [[ "$config_val" == *"=y" ]]; then
#                 continue
#             fi
#         fi
#         echo "$mod_name"
#     done <<< "$config_module_pairs" | sort -u
# }

#******************************************************************************
# Verify a single package
#******************************************************************************
verify_package() {
    local version="$1"
    local vendor="$2"
    local som="$3"
    local carrier="$4"

    reset_counters

    # Compute derived variables for this configuration
    local version_major=$(echo $version | awk -F '.' '{print $1}')

    # JetPack version infix
    local jetpack=$($_EGCFG "version.$version.jetpack" "$L4T_CONFIG_FILE" 2>/dev/null || echo "")
    local jp_infix=""
    [[ -n "$jetpack" ]] && jp_infix="-jp${jetpack}"

    # Directory naming based on vendor/SoM/carrier-board
    local linux_for_tegra_dir
    local vendor_source_dir=""
    local som_source_dir=""
    if [[ "$vendor" == "generic" ]]; then
        if [[ -n "$som" ]]; then
            local som_suffix=$(get_som_dir_suffix "$som")
            linux_for_tegra_dir=Linux_for_Tegra_${som_suffix}
            som_source_dir=Linux_for_Tegra_${som_suffix}
        else
            linux_for_tegra_dir=Linux_for_Tegra
        fi
    else
        local carrier_suffix=$(get_carrier_dir_suffix "$carrier")
        if [[ -n "$carrier_suffix" ]]; then
            linux_for_tegra_dir=Linux_for_Tegra_${vendor}_${carrier_suffix}
        else
            linux_for_tegra_dir=Linux_for_Tegra_${vendor}
        fi
        vendor_source_dir=Linux_for_Tegra_${vendor}
    fi

    local jetson_dir="$SCRIPT_DIR/$version"
    local rootfs_dir="$jetson_dir/${linux_for_tegra_dir}/rootfs"

    # Package naming (mirrors l4t_gen_delivery_package.sh)
    local package_name
    if [[ "$vendor" == "generic" ]]; then
        if [[ -n "$som" ]]; then
            package_name=jetson-l4t-${version}${jp_infix}-${som}-eg-cams
        else
            package_name=jetson-l4t-${version}${jp_infix}-eg-cams
        fi
    else
        local carrier_deb=$(echo "$carrier" | tr '_' '-')
        package_name=jetson-l4t-${version}${jp_infix}-${vendor}-${carrier_deb}-eg-cams
    fi

    local package_dir="$jetson_dir/$package_name"

    # Check if package directory exists
    if [[ ! -d "$package_dir" ]]; then
        echo -e "  ${YELLOW}[SKIPPED]${NC} $package_name - package directory not found"
        TOTAL_SKIPPED=$((TOTAL_SKIPPED + 1))
        return 2
    fi

    # Auto-detect standalone build
    local standalone_build=0
    local kernel_version
    local eg_kernel_version=$(ls "$rootfs_dir/lib/modules/" 2>/dev/null | grep -- '-eg$')
    if [[ -n "$eg_kernel_version" ]]; then
        standalone_build=1
        kernel_version="$eg_kernel_version"
    else
        kernel_version=$(ls "$rootfs_dir/lib/modules/" 2>/dev/null | grep -v -- '-eg$' | head -1)
    fi

    if [[ $VERBOSE -eq 1 ]]; then
        echo ""
        echo "  Version: $version (JetPack ${jetpack:-unknown})"
        echo "  Vendor: $vendor"
        [[ -n "$som" ]] && echo "  SoM: $som"
        echo "  Carrier board: $carrier"
        echo "  Kernel version: ${kernel_version:-unknown}"
        if [[ $standalone_build -eq 1 ]]; then
            echo "  Mode: standalone"
        else
            echo "  Mode: standard"
        fi
        echo ""
    fi

    # 1. Verify boot files
    if [[ $VERBOSE -eq 1 ]]; then
        echo "  --- Boot files ---"
    fi

    check_dir "$package_dir/boot/eg" "Boot EG directory"

    if [[ -d "$package_dir/boot/eg" ]]; then
        if [[ $standalone_build -eq 1 ]]; then
            check_file "$package_dir/boot/eg/Image" "Standalone kernel Image"
            check_file "$package_dir/boot/eg/initrd-eg" "Standalone initramfs"
        fi
    fi

    # Verify each expected DTBO file from Makefile
    # For SoM builds, look in the SoM-specific source dir; for vendor builds, use vendor dir
    local dtbo_source_dir="${som_source_dir:-$vendor_source_dir}"
    local expected_dtbo=$(get_expected_eg_dtbo "$version" "$dtbo_source_dir")
    local dtbo_count=0
    local dtbo_missing=0

    if [[ -n "$expected_dtbo" ]]; then
        while IFS= read -r dtbo_file; do
            dtbo_count=$((dtbo_count + 1))
            if [[ -f "$package_dir/boot/$dtbo_file" ]]; then
                if [[ $VERBOSE -eq 1 ]]; then
                    echo -e "  ${GREEN}[OK]${NC} $dtbo_file"
                fi
            else
                echo -e "  ${RED}[MISSING]${NC} $dtbo_file"
                dtbo_missing=$((dtbo_missing + 1))
                PKG_ERRORS=$((PKG_ERRORS + 1))
            fi
            PKG_CHECKS=$((PKG_CHECKS + 1))
        done <<< "$expected_dtbo"

        if [[ $dtbo_missing -eq 0 ]]; then
            if [[ $VERBOSE -eq 0 ]]; then
                echo -e "  ${GREEN}[OK]${NC} All $dtbo_count EG device tree overlays present"
            fi
        else
            echo -e "  ${RED}[ERROR]${NC} $dtbo_missing/$dtbo_count EG device tree overlays missing"
        fi
    else
        # Fallback: check if any EG dtbo files exist
        check_files_exist "$package_dir/boot" "*-eg-*.dtb*" "EG device tree overlays"
    fi

    # 2. Verify etc files
    if [[ $VERBOSE -eq 1 ]]; then
        echo "  --- Configuration files ---"
    fi

    check_file "$package_dir/etc/version_eg_cams" "Version info file"

    # 3. Verify kernel modules
    if [[ $VERBOSE -eq 1 ]]; then
        echo "  --- Kernel modules ---"
    fi

    local modules_dir="$package_dir/lib/modules"

    # Auto-detect EG kernel modules from sources (source-based detection).
    # Cross-references Exosens .c sources with the i2c Makefile to find EG modules.
    local eg_modules=""
    if [[ $standalone_build -eq 0 ]]; then
        # EG module list is always derived from the version-generic Makefile.
        # SoM/vendor layers contain NVIDIA stock Makefiles (no EG modules).
        local i2c_makefile=""
        for rel in "source/public/kernel/nvidia/drivers/media/i2c/Makefile" \
                   "source/nvidia-oot/drivers/media/i2c/Makefile"; do
            local candidate="$SCRIPT_DIR/sources/$version/Linux_for_Tegra/$rel"
            [[ -f "$candidate" ]] && i2c_makefile="$candidate"
        done
        if [[ -n "$i2c_makefile" ]]; then
            local eg_srcs=()
            while IFS= read -r f; do
                eg_srcs+=("$(basename "$f" .c)")
            done < <(find "$SCRIPT_DIR/sources" -path "*/drivers/media/i2c/*.c" 2>/dev/null)

            local makefile_joined
            makefile_joined=$(awk '{if(/\\$/) {printf "%s ", substr($0,1,length($0)-1)} else {print}}' "$i2c_makefile")

            declare -A _mod_srcs_v
            while IFS= read -r line; do
                line="${line%%#*}"
                if [[ "$line" =~ ^([a-zA-Z0-9_-]+)-[yo][^[:space:]=]*[[:space:]]*([:+]?=)[[:space:]]*(.*) ]]; then
                    local _m="${BASH_REMATCH[1]}"
                    for tok in ${BASH_REMATCH[3]}; do
                        [[ "$tok" == *.o ]] && _mod_srcs_v["$_m"]+=" $(basename "${tok%.o}")"
                    done
                fi
            done <<< "$makefile_joined"

            while IFS= read -r line; do
                line="${line%%#*}"
                if [[ "$line" =~ ^obj-[^+]*\+=[[:space:]]*([a-zA-Z0-9_-]+)\.o ]]; then
                    local _mod="${BASH_REMATCH[1]}"
                    local _srcs="${_mod_srcs_v[$_mod]:-$_mod}"
                    for _src in $_srcs; do
                        for _eg in "${eg_srcs[@]}"; do
                            if [[ "$_src" == "$_eg" ]]; then
                                eg_modules+="${_mod}"$'\n'
                                break 2
                            fi
                        done
                    done
                fi
            done <<< "$makefile_joined"
            unset _mod_srcs_v
            eg_modules=$(echo "$eg_modules" | sort -u)
        fi
    fi

    if [[ $standalone_build -eq 1 ]]; then
        check_dir "$modules_dir/$kernel_version" "Kernel modules directory"
        if [[ -d "$modules_dir/$kernel_version" ]]; then
            check_files_exist "$modules_dir/$kernel_version" "*.ko" "Kernel modules"
        fi
    else
        if [[ $version_major -ge 36 ]]; then
            local i2c_dir="$modules_dir/$kernel_version/updates/drivers/media/i2c"
            if [[ -n "$eg_modules" ]]; then
                while IFS= read -r mod_name; do
                    [[ -z "$mod_name" ]] && continue
                    check_file "$i2c_dir/${mod_name}.ko" "Exosens module ${mod_name}"
                done <<< "$eg_modules"
            fi
            check_file "$modules_dir/$kernel_version/updates/drivers/video/tegra/camera/tegra_camera_platform.ko" "Tegra camera platform module" 0
            check_file "$modules_dir/$kernel_version/updates/drivers/media/platform/tegra/camera/tegra-camera.ko" "Tegra camera module" 0
            check_file "$modules_dir/$kernel_version/updates/drivers/video/tegra/host/nvcsi/nvhost-nvcsi-t194.ko" "NVCSI module" 0
        else
            local i2c_dir="$modules_dir/$kernel_version/kernel/drivers/media/i2c"
            if [[ -n "$eg_modules" ]]; then
                while IFS= read -r mod_name; do
                    [[ -z "$mod_name" ]] && continue
                    check_file "$i2c_dir/${mod_name}.ko" "Exosens module ${mod_name}"
                done <<< "$eg_modules"
            fi
        fi
    fi

    # 4. Verify source files
    if [[ $VERBOSE -eq 1 ]]; then
        echo "  --- Source files ---"
    fi

    check_dir "$package_dir/usr" "User binaries directory"
    if [[ -d "$package_dir/usr/bin" ]]; then
        check_file "$package_dir/usr/bin/eg_dt_camera_config_set.sh" "Camera config set script"
        check_file "$package_dir/usr/bin/eg_dt_camera_config_get.sh" "Camera config get script"
        check_file "$package_dir/usr/bin/detect_jetson_board.sh" "Jetson board detection script"
    fi

    check_dir "$package_dir/opt/eg" "EG configuration directory"
    if [[ -d "$package_dir/opt/eg" ]]; then
        check_dir "$package_dir/opt/eg/jetson-io" "Jetson-IO configuration"
        check_dir "$package_dir/opt/eg/doc" "Documentation" 0
    fi

    # Update totals
    TOTAL_CHECKS=$((TOTAL_CHECKS + PKG_CHECKS))
    TOTAL_ERRORS=$((TOTAL_ERRORS + PKG_ERRORS))
    TOTAL_WARNINGS=$((TOTAL_WARNINGS + PKG_WARNINGS))

    # Return result
    if [[ $PKG_ERRORS -eq 0 ]]; then
        TOTAL_PASSED=$((TOTAL_PASSED + 1))
        return 0
    else
        TOTAL_FAILED=$((TOTAL_FAILED + 1))
        return 1
    fi
}

#******************************************************************************
# Main execution
#******************************************************************************
echo "============================================"
echo -e "${CYAN}L4T Package Verification${NC}"
echo "============================================"
echo ""
echo "Configurations to verify: $config_count"
if [[ $VERBOSE -eq 1 ]]; then
    echo "Mode: verbose"
fi
echo ""

config_index=0
for config in $configs; do
    config_index=$((config_index + 1))
    parse_config "$config"

    som_label="${CFG_SOM:+/$CFG_SOM}"
    echo -n -e "[$config_index/$config_count] ${CYAN}$CFG_VERSION${NC} / $CFG_VENDOR${som_label} / $CFG_CARRIER: "

    if verify_package "$CFG_VERSION" "$CFG_VENDOR" "$CFG_SOM" "$CFG_CARRIER"; then
        echo -e "${GREEN}PASSED${NC} ($PKG_CHECKS checks)"
    elif [[ $? -eq 2 ]]; then
        # Skipped (message already printed by verify_package)
        :
    else
        echo -e "${RED}FAILED${NC} ($PKG_ERRORS errors, $PKG_WARNINGS warnings)"
    fi
done

#******************************************************************************
# Summary
#******************************************************************************
echo ""
echo "============================================"
echo -e "${CYAN}SUMMARY${NC}"
echo "============================================"
echo ""
echo "Total configurations: $config_count"
echo -e "  ${GREEN}Passed: $TOTAL_PASSED${NC}"
echo -e "  ${RED}Failed: $TOTAL_FAILED${NC}"
echo -e "  ${YELLOW}Skipped: $TOTAL_SKIPPED${NC}"
echo ""
echo "Total checks: $TOTAL_CHECKS"
echo -e "Total errors: $([ $TOTAL_ERRORS -eq 0 ] && echo -e "${GREEN}$TOTAL_ERRORS${NC}" || echo -e "${RED}$TOTAL_ERRORS${NC}")"
echo -e "Total warnings: $([ $TOTAL_WARNINGS -eq 0 ] && echo -e "${GREEN}$TOTAL_WARNINGS${NC}" || echo -e "${YELLOW}$TOTAL_WARNINGS${NC}")"
echo ""

if [[ $TOTAL_FAILED -eq 0 && $TOTAL_PASSED -gt 0 ]]; then
    echo -e "${GREEN}All packages verified successfully${NC}"
    exit 0
elif [[ $TOTAL_PASSED -eq 0 && $TOTAL_SKIPPED -eq $config_count ]]; then
    echo -e "${YELLOW}No packages found to verify${NC}"
    exit 0
else
    echo -e "${RED}Some packages failed verification${NC}"
    exit 1
fi
