#!/bin/bash
#******************************************************************************
# l4t_verify_packages.sh - Verify Debian packages generated by l4t_gen_delivery_package.sh
#
# Usage:
#   ./l4t_verify_packages.sh [-v <version>] [-V <vendor>] [-c <carrier-board>] [--verbose]
#
# This script verifies that the installation directory used for Debian package
# generation contains all expected files.
#
# Options:
#   -v, --l4t-version VERSION   Version filter (supports wildcards: 36.*, 35.6.*)
#   -V, --vendor VENDOR         Vendor filter: generic, forecr (default: all)
#   -c, --carrier-board BOARD   Carrier board filter (default: all for vendor)
#   --verbose                   Show detailed file paths
#   --list                      List matching configurations and exit
#   -h, --help                  Show this help message
#
# Examples:
#   ./l4t_verify_packages.sh                        # Verify all packages
#   ./l4t_verify_packages.sh -v 36.4.3              # Verify 36.4.3 all vendors
#   ./l4t_verify_packages.sh -v 36.4.3 -V forecr    # Verify 36.4.3 forecr only
#   ./l4t_verify_packages.sh -v "36.*" --verbose    # Verify all 36.x with details
#******************************************************************************

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source unified environment (provides enumeration functions)
. "$SCRIPT_DIR/l4t_environment.sh"

#******************************************************************************
# Default values
#******************************************************************************
VERSION_FILTER=""
VENDOR_FILTER=""
CARRIER_FILTER=""
VERBOSE=0
LIST_ONLY=0

#******************************************************************************
# Colors
#******************************************************************************
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

#******************************************************************************
# Help function
#******************************************************************************
show_help() {
    head -24 "$0" | tail -n +2 | sed 's/^#//' | sed 's/^\*//g'
    echo ""
    local all_versions=$(get_all_versions)
    echo "Available versions: $all_versions"
    echo ""
    echo "Version-vendor support:"
    for v in $all_versions; do
        local vendors=$(get_vendors_for_version "$v")
        echo "  $v: $vendors"
    done
}

#******************************************************************************
# Parse arguments
#******************************************************************************
while [[ $# -gt 0 ]]; do
    case "$1" in
        -v|--l4t-version)
            VERSION_FILTER="$2"
            shift 2
            ;;
        -V|--vendor)
            VENDOR_FILTER="$2"
            shift 2
            ;;
        -c|--carrier-board)
            CARRIER_FILTER="$2"
            shift 2
            ;;
        --verbose)
            VERBOSE=1
            shift
            ;;
        --list)
            LIST_ONLY=1
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo "Error: Unknown argument: $1"
            echo "Use --help for usage information."
            exit 1
            ;;
    esac
done

#******************************************************************************
# Validate filters
#******************************************************************************
if ! validate_filters "$VERSION_FILTER" "$VENDOR_FILTER" "$CARRIER_FILTER"; then
    exit 1
fi

#******************************************************************************
# Get configurations to process
#******************************************************************************
configs=$(enumerate_configs "$VERSION_FILTER" "$VENDOR_FILTER" "$CARRIER_FILTER")
config_count=$(echo "$configs" | wc -l)

#******************************************************************************
# List mode
#******************************************************************************
if [[ $LIST_ONLY -eq 1 ]]; then
    echo "Matching configurations ($config_count):"
    echo ""
    printf "%-12s %-12s %-15s\n" "VERSION" "VENDOR" "CARRIER"
    echo "-----------------------------------------------"
    for config in $configs; do
        parse_config "$config"
        printf "%-12s %-12s %-15s\n" "$CFG_VERSION" "$CFG_VENDOR" "$CFG_CARRIER"
    done
    exit 0
fi

#******************************************************************************
# Counters
#******************************************************************************
TOTAL_ERRORS=0
TOTAL_WARNINGS=0
TOTAL_CHECKS=0
TOTAL_PASSED=0
TOTAL_FAILED=0
TOTAL_SKIPPED=0

#******************************************************************************
# Helper functions
#******************************************************************************
# Reset per-package counters
reset_counters() {
    PKG_ERRORS=0
    PKG_WARNINGS=0
    PKG_CHECKS=0
}

# Extract expected EG DTBO files from Makefiles
# Args: version, vendor_source_dir (empty for generic)
# Returns: list of expected dtbo filenames (one per line)
get_expected_eg_dtbo() {
    local version="$1"
    local vendor_source_dir="$2"

    local source_base="$SCRIPT_DIR/sources/$version"
    local makefiles=""

    # Determine which source directory to use
    if [[ -n "$vendor_source_dir" ]]; then
        source_base="$source_base/$vendor_source_dir"
    else
        source_base="$source_base/Linux_for_Tegra"
    fi

    # Find all Makefiles containing dtbo-y and eg patterns
    if [[ -d "$source_base" ]]; then
        makefiles=$(find "$source_base" -name "Makefile" -type f -exec grep -l "dtbo.*eg" {} \; 2>/dev/null)
    fi

    # Extract dtbo-y lines containing -eg- patterns
    for makefile in $makefiles; do
        grep -E 'dtbo-.*\+=' "$makefile" 2>/dev/null | \
            grep -E '\-eg\-' | \
            sed -E 's/.*\+= *([^ ]+\.dtbo).*/\1/' | \
            sort -u
    done | sort -u
}

check_file() {
    local file="$1"
    local description="$2"
    local required="${3:-1}"  # 1=required, 0=optional

    PKG_CHECKS=$((PKG_CHECKS + 1))

    if [[ -f "$file" ]]; then
        if [[ $VERBOSE -eq 1 ]]; then
            echo -e "  ${GREEN}[OK]${NC} $description"
            echo "       $file"
        fi
        return 0
    else
        if [[ $required -eq 1 ]]; then
            echo -e "  ${RED}[MISSING]${NC} $description"
            if [[ $VERBOSE -eq 1 ]]; then
                echo "       Expected: $file"
            fi
            PKG_ERRORS=$((PKG_ERRORS + 1))
        else
            if [[ $VERBOSE -eq 1 ]]; then
                echo -e "  ${YELLOW}[OPTIONAL]${NC} $description (not found)"
            fi
            PKG_WARNINGS=$((PKG_WARNINGS + 1))
        fi
        return 1
    fi
}

check_dir() {
    local dir="$1"
    local description="$2"
    local required="${3:-1}"

    PKG_CHECKS=$((PKG_CHECKS + 1))

    if [[ -d "$dir" ]]; then
        if [[ $VERBOSE -eq 1 ]]; then
            local count=$(find "$dir" -type f 2>/dev/null | wc -l)
            echo -e "  ${GREEN}[OK]${NC} $description ($count files)"
            echo "       $dir"
        fi
        return 0
    else
        if [[ $required -eq 1 ]]; then
            echo -e "  ${RED}[MISSING]${NC} $description"
            if [[ $VERBOSE -eq 1 ]]; then
                echo "       Expected: $dir"
            fi
            PKG_ERRORS=$((PKG_ERRORS + 1))
        else
            if [[ $VERBOSE -eq 1 ]]; then
                echo -e "  ${YELLOW}[OPTIONAL]${NC} $description (not found)"
            fi
            PKG_WARNINGS=$((PKG_WARNINGS + 1))
        fi
        return 1
    fi
}

check_files_exist() {
    local dir="$1"
    local pattern="$2"
    local description="$3"
    local required="${4:-1}"

    PKG_CHECKS=$((PKG_CHECKS + 1))

    local files=$(find "$dir" -name "$pattern" -type f 2>/dev/null)
    local count=0
    if [[ -n "$files" ]]; then
        count=$(echo "$files" | wc -l)
    fi

    if [[ $count -gt 0 ]]; then
        if [[ $VERBOSE -eq 1 ]]; then
            echo -e "  ${GREEN}[OK]${NC} $description ($count files matching '$pattern')"
            echo "$files" | head -5 | sed 's/^/       /'
            if [[ $count -gt 5 ]]; then
                echo "       ... and $((count - 5)) more"
            fi
        fi
        return 0
    else
        if [[ $required -eq 1 ]]; then
            echo -e "  ${RED}[MISSING]${NC} $description (no files matching '$pattern')"
            PKG_ERRORS=$((PKG_ERRORS + 1))
        else
            if [[ $VERBOSE -eq 1 ]]; then
                echo -e "  ${YELLOW}[OPTIONAL]${NC} $description (no files matching '$pattern')"
            fi
            PKG_WARNINGS=$((PKG_WARNINGS + 1))
        fi
        return 1
    fi
}

# Auto-detect Exosens camera modules from patch files
# Args: version, vendor
# Outputs module names (without .ko) to stdout, one per line
get_eg_modules_from_patch() {
    local version="$1"
    local vendor="$2"
    local version_major=$(echo "$version" | awk -F '.' '{print $1}')

    # Compute extended version (same logic as l4t_environment.sh)
    local version_extended="$version"
    if [[ "$vendor" != "generic" ]]; then
        version_extended="${version}_${vendor}"
    fi

    # Determine patch filename based on L4T major version
    local patch_file
    if [[ $version_major -ge 36 ]]; then
        patch_file="$SCRIPT_DIR/patches/${version_extended}/source_nvidia-oot_drivers_media_i2c.patch"
    else
        patch_file="$SCRIPT_DIR/patches/${version_extended}/source_public_kernel_nvidia_drivers_media_i2c.patch"
    fi

    if [[ -f "$patch_file" ]]; then
        grep '^+obj-' "$patch_file" | sed 's/.*+=//' | tr -d '[:blank:]' | sed 's/\.o$//' | sort -u
    fi
}

#******************************************************************************
# Verify a single package
#******************************************************************************
verify_package() {
    local version="$1"
    local vendor="$2"
    local carrier="$3"

    reset_counters

    # Compute derived variables for this configuration
    local version_major=$(echo $version | awk -F '.' '{print $1}')

    # Directory naming based on vendor/carrier-board
    local linux_for_tegra_dir
    local vendor_source_dir=""
    if [[ "$vendor" == "generic" ]]; then
        linux_for_tegra_dir=Linux_for_Tegra
    else
        local carrier_suffix=$(get_carrier_dir_suffix "$carrier")
        if [[ -n "$carrier_suffix" ]]; then
            linux_for_tegra_dir=Linux_for_Tegra_${vendor}_${carrier_suffix}
        else
            linux_for_tegra_dir=Linux_for_Tegra_${vendor}
        fi
        vendor_source_dir=Linux_for_Tegra_${vendor}
    fi

    local jetson_dir="$SCRIPT_DIR/$version"
    local rootfs_dir="$jetson_dir/${linux_for_tegra_dir}/rootfs"

    # Package naming
    local package_name
    if [[ "$vendor" == "generic" ]]; then
        package_name=jetson-l4t-${version}-eg-cams
    else
        local carrier_deb=$(echo "$carrier" | tr '_' '-')
        package_name=jetson-l4t-${version}-${vendor}-${carrier_deb}-eg-cams
    fi

    local package_dir="$jetson_dir/$package_name"

    # Check if package directory exists
    if [[ ! -d "$package_dir" ]]; then
        echo -e "  ${YELLOW}[SKIPPED]${NC} $package_name - package directory not found"
        TOTAL_SKIPPED=$((TOTAL_SKIPPED + 1))
        return 2
    fi

    # Auto-detect standalone build
    local standalone_build=0
    local kernel_version
    local eg_kernel_version=$(ls "$rootfs_dir/lib/modules/" 2>/dev/null | grep -- '-eg$')
    if [[ -n "$eg_kernel_version" ]]; then
        standalone_build=1
        kernel_version="$eg_kernel_version"
    else
        kernel_version=$(ls "$rootfs_dir/lib/modules/" 2>/dev/null | grep -v -- '-eg$' | head -1)
    fi

    if [[ $VERBOSE -eq 1 ]]; then
        echo ""
        echo "  Version: $version"
        echo "  Vendor: $vendor"
        echo "  Carrier board: $carrier"
        echo "  Kernel version: ${kernel_version:-unknown}"
        if [[ $standalone_build -eq 1 ]]; then
            echo "  Mode: standalone"
        else
            echo "  Mode: standard"
        fi
        echo ""
    fi

    # 1. Verify boot files
    if [[ $VERBOSE -eq 1 ]]; then
        echo "  --- Boot files ---"
    fi

    check_dir "$package_dir/boot/eg" "Boot EG directory"

    if [[ -d "$package_dir/boot/eg" ]]; then
        if [[ $standalone_build -eq 1 ]]; then
            check_file "$package_dir/boot/eg/Image" "Standalone kernel Image"
            check_file "$package_dir/boot/eg/initrd-eg" "Standalone initramfs"
        fi
    fi

    # Verify each expected DTBO file from Makefile
    local expected_dtbo=$(get_expected_eg_dtbo "$version" "$vendor_source_dir")
    local dtbo_count=0
    local dtbo_missing=0

    if [[ -n "$expected_dtbo" ]]; then
        while IFS= read -r dtbo_file; do
            dtbo_count=$((dtbo_count + 1))
            if [[ -f "$package_dir/boot/$dtbo_file" ]]; then
                if [[ $VERBOSE -eq 1 ]]; then
                    echo -e "  ${GREEN}[OK]${NC} $dtbo_file"
                fi
            else
                echo -e "  ${RED}[MISSING]${NC} $dtbo_file"
                dtbo_missing=$((dtbo_missing + 1))
                PKG_ERRORS=$((PKG_ERRORS + 1))
            fi
            PKG_CHECKS=$((PKG_CHECKS + 1))
        done <<< "$expected_dtbo"

        if [[ $dtbo_missing -eq 0 ]]; then
            if [[ $VERBOSE -eq 0 ]]; then
                echo -e "  ${GREEN}[OK]${NC} All $dtbo_count EG device tree overlays present"
            fi
        else
            echo -e "  ${RED}[ERROR]${NC} $dtbo_missing/$dtbo_count EG device tree overlays missing"
        fi
    else
        # Fallback: check if any EG dtbo files exist
        check_files_exist "$package_dir/boot" "*-eg-*.dtb*" "EG device tree overlays"
    fi

    # 2. Verify etc files
    if [[ $VERBOSE -eq 1 ]]; then
        echo "  --- Configuration files ---"
    fi

    check_file "$package_dir/etc/version_eg_cams" "Version info file"

    # 3. Verify kernel modules
    if [[ $VERBOSE -eq 1 ]]; then
        echo "  --- Kernel modules ---"
    fi

    local modules_dir="$package_dir/lib/modules"

    # Auto-detect Exosens camera modules from patch files
    local eg_modules
    eg_modules=$(get_eg_modules_from_patch "$version" "$vendor")

    if [[ $standalone_build -eq 1 ]]; then
        check_dir "$modules_dir/$kernel_version" "Kernel modules directory"
        if [[ -d "$modules_dir/$kernel_version" ]]; then
            if [[ -n "$eg_modules" ]]; then
                while IFS= read -r mod_name; do
                    [[ -z "$mod_name" ]] && continue
                    check_files_exist "$modules_dir/$kernel_version" "${mod_name}.ko" "Exosens module ${mod_name}"
                done <<< "$eg_modules"
            else
                echo -e "  ${YELLOW}[WARN]${NC} Could not auto-detect modules from patch file"
                PKG_WARNINGS=$((PKG_WARNINGS + 1))
            fi
        fi
    else
        if [[ $version_major -ge 36 ]]; then
            local i2c_dir="$modules_dir/$kernel_version/updates/drivers/media/i2c"
            if [[ -n "$eg_modules" ]]; then
                while IFS= read -r mod_name; do
                    [[ -z "$mod_name" ]] && continue
                    check_file "$i2c_dir/${mod_name}.ko" "Exosens module ${mod_name}"
                done <<< "$eg_modules"
            else
                echo -e "  ${YELLOW}[WARN]${NC} Could not auto-detect modules from patch file"
                PKG_WARNINGS=$((PKG_WARNINGS + 1))
            fi
            check_file "$modules_dir/$kernel_version/updates/drivers/video/tegra/camera/tegra_camera_platform.ko" "Tegra camera platform module" 0
            check_file "$modules_dir/$kernel_version/updates/drivers/media/platform/tegra/camera/tegra-camera.ko" "Tegra camera module" 0
            check_file "$modules_dir/$kernel_version/updates/drivers/video/tegra/host/nvcsi/nvhost-nvcsi-t194.ko" "NVCSI module" 0
        else
            local i2c_dir="$modules_dir/$kernel_version/kernel/drivers/media/i2c"
            if [[ -n "$eg_modules" ]]; then
                while IFS= read -r mod_name; do
                    [[ -z "$mod_name" ]] && continue
                    check_file "$i2c_dir/${mod_name}.ko" "Exosens module ${mod_name}"
                done <<< "$eg_modules"
            else
                echo -e "  ${YELLOW}[WARN]${NC} Could not auto-detect modules from patch file"
                PKG_WARNINGS=$((PKG_WARNINGS + 1))
            fi
        fi
    fi

    # 4. Verify source files
    if [[ $VERBOSE -eq 1 ]]; then
        echo "  --- Source files ---"
    fi

    check_dir "$package_dir/usr" "User binaries directory"
    if [[ -d "$package_dir/usr/bin" ]]; then
        check_file "$package_dir/usr/bin/eg_dt_camera_config_set.sh" "Camera config set script"
        check_file "$package_dir/usr/bin/eg_dt_camera_config_get.sh" "Camera config get script"
        check_file "$package_dir/usr/bin/detect_jetson_board.sh" "Jetson board detection script"
    fi

    check_dir "$package_dir/opt/eg" "EG configuration directory"
    if [[ -d "$package_dir/opt/eg" ]]; then
        check_dir "$package_dir/opt/eg/jetson-io" "Jetson-IO configuration"
        check_dir "$package_dir/opt/eg/doc" "Documentation" 0
    fi

    # Update totals
    TOTAL_CHECKS=$((TOTAL_CHECKS + PKG_CHECKS))
    TOTAL_ERRORS=$((TOTAL_ERRORS + PKG_ERRORS))
    TOTAL_WARNINGS=$((TOTAL_WARNINGS + PKG_WARNINGS))

    # Return result
    if [[ $PKG_ERRORS -eq 0 ]]; then
        TOTAL_PASSED=$((TOTAL_PASSED + 1))
        return 0
    else
        TOTAL_FAILED=$((TOTAL_FAILED + 1))
        return 1
    fi
}

#******************************************************************************
# Main execution
#******************************************************************************
echo "============================================"
echo -e "${CYAN}L4T Package Verification${NC}"
echo "============================================"
echo ""
echo "Configurations to verify: $config_count"
if [[ $VERBOSE -eq 1 ]]; then
    echo "Mode: verbose"
fi
echo ""

config_index=0
for config in $configs; do
    config_index=$((config_index + 1))
    parse_config "$config"

    echo -n -e "[$config_index/$config_count] ${CYAN}$CFG_VERSION${NC} / $CFG_VENDOR / $CFG_CARRIER: "

    if verify_package "$CFG_VERSION" "$CFG_VENDOR" "$CFG_CARRIER"; then
        echo -e "${GREEN}PASSED${NC} ($PKG_CHECKS checks)"
    elif [[ $? -eq 2 ]]; then
        # Skipped (message already printed by verify_package)
        :
    else
        echo -e "${RED}FAILED${NC} ($PKG_ERRORS errors, $PKG_WARNINGS warnings)"
    fi
done

#******************************************************************************
# Summary
#******************************************************************************
echo ""
echo "============================================"
echo -e "${CYAN}SUMMARY${NC}"
echo "============================================"
echo ""
echo "Total configurations: $config_count"
echo -e "  ${GREEN}Passed: $TOTAL_PASSED${NC}"
echo -e "  ${RED}Failed: $TOTAL_FAILED${NC}"
echo -e "  ${YELLOW}Skipped: $TOTAL_SKIPPED${NC}"
echo ""
echo "Total checks: $TOTAL_CHECKS"
echo -e "Total errors: $([ $TOTAL_ERRORS -eq 0 ] && echo -e "${GREEN}$TOTAL_ERRORS${NC}" || echo -e "${RED}$TOTAL_ERRORS${NC}")"
echo -e "Total warnings: $([ $TOTAL_WARNINGS -eq 0 ] && echo -e "${GREEN}$TOTAL_WARNINGS${NC}" || echo -e "${YELLOW}$TOTAL_WARNINGS${NC}")"
echo ""

if [[ $TOTAL_FAILED -eq 0 && $TOTAL_PASSED -gt 0 ]]; then
    echo -e "${GREEN}All packages verified successfully${NC}"
    exit 0
elif [[ $TOTAL_PASSED -eq 0 && $TOTAL_SKIPPED -eq $config_count ]]; then
    echo -e "${YELLOW}No packages found to verify${NC}"
    exit 0
else
    echo -e "${RED}Some packages failed verification${NC}"
    exit 1
fi
