#!/bin/bash
#******************************************************************************
# l4t_prepare.sh - Prepare L4T environment for Exosens camera builds
#
# This script downloads and extracts the NVIDIA L4T BSP, toolchain, and
# kernel sources.
#
# Usage:
#   ./l4t_prepare.sh -v <version> [-V <vendor>] [-c <carrier-board>]
#
# Examples:
#   ./l4t_prepare.sh -v 36.4.3
#   ./l4t_prepare.sh -v 36.4.3 -V forecr
#   ./l4t_prepare.sh --l4t-version 36.4.3 --vendor forecr --carrier-board dsboard_ornxs
#
# Performance:
#   Install parallel decompression tools for faster extraction:
#     sudo apt install lbzip2 pigz
#******************************************************************************

. l4t_environment.sh
l4t_init "$@"

#******************************************************************************
# Optimized tar extraction using parallel decompression when available
# Usage: fast_tar_extract <archive_file>
#******************************************************************************
fast_tar_extract() {
    local archive="$1"
    local ext="${archive##*.}"

    case "$ext" in
        tbz2|bz2)
            # Use parallel bzip2 if available (lbzip2 is fastest)
            if command -v lbzip2 &>/dev/null; then
                tar -I lbzip2 -xf "$archive"
            elif command -v pbzip2 &>/dev/null; then
                tar -I pbzip2 -xf "$archive"
            else
                tar -xjf "$archive"
            fi
            ;;
        tgz|gz)
            # Use parallel gzip if available
            if command -v pigz &>/dev/null; then
                tar -I pigz -xf "$archive"
            else
                tar -xzf "$archive"
            fi
            ;;
        xz)
            # Use parallel xz if available
            if command -v pixz &>/dev/null; then
                tar -I pixz -xf "$archive"
            else
                tar -xJf "$archive"
            fi
            ;;
        *)
            tar -xf "$archive"
            ;;
    esac
}

# Show which decompression tools are available
echo "Decompression tools: $(command -v lbzip2 >/dev/null && echo 'lbzip2' || echo 'bzip2') | $(command -v pigz >/dev/null && echo 'pigz' || echo 'gzip')"

update_status "Initializing..."

# A vendor source layer built from a vendor archive (Connect Tech) is a derived
# artefact, not EG source: it is gitignored and regenerated by the extractors at
# the end of this script. If the build tree does not exist yet — a genuinely
# fresh prepare, e.g. after deleting <version>/ — any layer left over from a
# previous run may have been produced from a different archive or a different
# extraction scope, so wipe it here and let it be regenerated rather than
# silently reusing it.
if [[ -n "$VENDOR_SOURCE_DIR" && "$VENDOR" == cti* ]]; then
   _vendor_layer="$ROOT_DIR/sources/$L4T_VERSION/$VENDOR_SOURCE_DIR"
   # .prepare_done (written on the very last line of this script) means a
   # prepare ran to completion for THIS configuration — unlike .bsp_done, which
   # is written early and would also be present after a run interrupted before
   # the vendor extraction.
   if [[ ! -f "$JETSON_DIR/$LINUX_FOR_TEGRA_DIR/.prepare_done" && -d "$_vendor_layer" ]]; then
      echo "  Fresh prepare: removing stale vendor source layer sources/$L4T_VERSION/$VENDOR_SOURCE_DIR"
      rm -rf "$_vendor_layer"
   fi
fi

mkdir -p $JETSON_DIR

# PKG_ARCHIVE_DIR may include a SoM subdir (e.g. archives/32.7.1/t186/)
# when the version ships separate BSP packages per SoM (sources_by_som).
mkdir -p "$PKG_ARCHIVE_DIR"

#----------------------#
# Get the Nvidia SDK   #
#----------------------#
cd ${JETSON_DIR}

if [[ ! -f $PKG_ARCHIVE_DIR/${L4T_RELEASE_PACKAGE} ]]; then
   update_status "Downloading BSP..."
   wget -q $L4T_RELEASE_PACKAGE_URL -O $PKG_ARCHIVE_DIR/${L4T_RELEASE_PACKAGE}
fi
if [[ ! -f $PKG_ARCHIVE_DIR/${SAMPLE_FS_PACKAGE} ]]; then
   update_status "Downloading rootfs..."
   wget -q $SAMPLE_FS_PACKAGE_URL -O $PKG_ARCHIVE_DIR/${SAMPLE_FS_PACKAGE}
fi
if [[ ! -f $PKG_ARCHIVE_DIR/${JETSON_PUBLIC_SOURCES} ]]; then
   update_status "Downloading sources..."
   wget -q $JETSON_PUBLIC_SOURCES_URL -O $PKG_ARCHIVE_DIR/${JETSON_PUBLIC_SOURCES}
fi

if [[ -f $JETSON_DIR/$LINUX_FOR_TEGRA_DIR/.bsp_done ]]; then
   update_status "BSP already set up, skipping"
else
   # Clean up any partial previous attempt
   sudo rm -rf $JETSON_DIR/tmp_$LINUX_FOR_TEGRA_DIR
   if [[ ! -d $JETSON_DIR/$LINUX_FOR_TEGRA_DIR ]]; then
      mkdir $JETSON_DIR/tmp_$LINUX_FOR_TEGRA_DIR
      cd $JETSON_DIR/tmp_$LINUX_FOR_TEGRA_DIR
      update_status "Extracting BSP..."
      fast_tar_extract "$PKG_ARCHIVE_DIR/${L4T_RELEASE_PACKAGE}"
      sudo mv Linux_for_Tegra $JETSON_DIR/$LINUX_FOR_TEGRA_DIR
      cd $JETSON_DIR
      sudo rm -rf tmp_$LINUX_FOR_TEGRA_DIR
   fi
   cd ${JETSON_DIR}/${LINUX_FOR_TEGRA_DIR}/rootfs/
   update_status "Extracting rootfs..."
   sudo tar -I lbzip2 -xpf "$PKG_ARCHIVE_DIR/${SAMPLE_FS_PACKAGE}" 2>/dev/null \
      || sudo tar -xpjf "$PKG_ARCHIVE_DIR/${SAMPLE_FS_PACKAGE}"
   cd ..
   update_status "Applying binaries..."
   sudo ./apply_binaries.sh > /dev/null 2>&1
   touch $JETSON_DIR/$LINUX_FOR_TEGRA_DIR/.bsp_done
fi

# Get toolchain
# The toolchain is shared across all vendor builds for a given L4T version.
# Use a version-scoped lock to avoid races when multiple vendors run --prepare
# in parallel (e.g. generic + forecr for the same version).
cd $JETSON_DIR
if [[ ! -f $ARCHIVE_DIR/$L4T_VERSION/${JETSON_TOOCHAIN_ARCHIVE} ]]; then
   update_status "Downloading toolchain..."
   wget -q $JETSON_TOOCHAIN_ARCHIVE_URL -O $ARCHIVE_DIR/$L4T_VERSION/${JETSON_TOOCHAIN_ARCHIVE}
fi
(
   flock -x 200
   if [[ -f $JETSON_DIR/.toolchain_done ]]; then
      update_status "Toolchain already extracted, skipping"
   else
      rm -rf $JETSON_DIR/$TOOLCHAIN_DIR
      mkdir $JETSON_DIR/$TOOLCHAIN_DIR
      cd $JETSON_DIR/$TOOLCHAIN_DIR
      update_status "Extracting toolchain..."
      fast_tar_extract "$ARCHIVE_DIR/$L4T_VERSION/$JETSON_TOOCHAIN_ARCHIVE"
      cd $JETSON_DIR
      touch .toolchain_done
   fi
) 200>"$JETSON_DIR/.toolchain_lock"

# Decompress Linux sources
cd $JETSON_DIR

if [[ -f $JETSON_DIR/$LINUX_FOR_TEGRA_DIR/.public_sources_done ]]; then
   update_status "Public sources already extracted, skipping"
else
   sudo rm -rf tmp_$LINUX_FOR_TEGRA_DIR
   mkdir tmp_$LINUX_FOR_TEGRA_DIR
   cd tmp_$LINUX_FOR_TEGRA_DIR
   update_status "Extracting public sources..."
   fast_tar_extract "$PKG_ARCHIVE_DIR/${JETSON_PUBLIC_SOURCES}"
   update_status "Copying sources..."
   rsync -aHAX Linux_for_Tegra/* ../${LINUX_FOR_TEGRA_DIR}/
   cd $JETSON_DIR
   sudo rm -rf tmp_$LINUX_FOR_TEGRA_DIR
   touch $JETSON_DIR/$LINUX_FOR_TEGRA_DIR/.public_sources_done
fi

cd $ROOT_DIR
# Re-initialize to update L4T_SRC path after extraction
. l4t_environment.sh
l4t_init "$@"
cd $L4T_SRC
mkdir -p build
mkdir -p modules

if [[ -f .kernel_src_done ]]; then
   update_status "Kernel sources already extracted, skipping"
else
   rm -rf kernel
   update_status "Extracting kernel sources..."
   fast_tar_extract kernel_src.tbz2
   touch .kernel_src_done
fi

if [[ -f kernel_oot_modules_src.tbz2 ]]; then
   if [[ -f .kernel_oot_done ]]; then
      update_status "OOT modules already extracted, skipping"
   else
      rm -rf nvidia-oot kernel-devicetree
      update_status "Extracting OOT modules..."
      fast_tar_extract kernel_oot_modules_src.tbz2
      touch .kernel_oot_done
   fi
fi
if [[ -f nvidia_kernel_display_driver_source.tbz2 ]]; then
   if [[ -f .nvidia_display_driver_done ]]; then
      update_status "Display driver already extracted, skipping"
   else
      rm -rf nvdisplay
      update_status "Extracting display driver..."
      fast_tar_extract nvidia_kernel_display_driver_source.tbz2
      touch .nvidia_display_driver_done
   fi
fi

if [[ -f nvidia_unified_gpu_display_driver_source.tbz2 ]]; then
   if [[ -f .nvidia_unified_gpu_display_driver_done ]]; then
      update_status "Unified GPU display driver already extracted, skipping"
   else
      rm -rf unifiedgpudisp
      update_status "Extracting unified GPU display driver..."
      fast_tar_extract nvidia_unified_gpu_display_driver_source.tbz2
      touch .nvidia_unified_gpu_display_driver_done
   fi
fi

# Connect Tech: the two build variants each need their own archive, handled
# independently — they are NOT interchangeable.
#
#  - cti_pristine (pristine_kernel=1): CTI ships a precompiled kernel/nvidia-oot
#    with no source (see cti_pristine_kernel_porting.md in shared memory), so our
#    EG modules are compiled against its real headers. That archive is CTI's own
#    public BSP release at a known url, so it is downloaded here like the NVIDIA
#    archives above, then reduced to the 2 header .deb packages.
#
#  - cti (pristine_kernel=0): CTI's real GPL kernel sources, used as a normal
#    vendor source layer. CONFIDENTIAL — no url is configured, so it is never
#    downloaded; it must be placed manually under archives/CTI/. Missing is not
#    an error here (the extractor warns and returns 0): enumerate_configs
#    already drops this configuration entirely when neither the archive nor its
#    delta cache is present.
if [[ "$VENDOR" == cti* ]]; then
   CTI_ARCHIVE_DIR="$ARCHIVE_DIR/CTI"
   mkdir -p "$CTI_ARCHIVE_DIR"

   if [[ -n "$VENDOR_ARCHIVE_URL" ]] && [[ ! -f "$CTI_ARCHIVE_DIR/$VENDOR_ARCHIVE" ]]; then
      update_status "Downloading CTI archive..."
      wget -q "$VENDOR_ARCHIVE_URL" -O "$CTI_ARCHIVE_DIR/$VENDOR_ARCHIVE"
   fi

   if [[ "$PRISTINE_KERNEL" == "1" ]]; then
      if [[ ! -f "$CTI_ARCHIVE_DIR/$VENDOR_ARCHIVE" ]]; then
         echo "Error: CTI archive not found: $CTI_ARCHIVE_DIR/$VENDOR_ARCHIVE" >&2
         echo "  (no url configured in eg_config.yaml — place it there manually)" >&2
         exit 1
      fi
      update_status "Extracting CTI headers..."
      if ! "$ROOT_DIR/tools/extract_cti_headers.sh" "$L4T_VERSION" "$CTI_ARCHIVE_DIR/$VENDOR_ARCHIVE"; then
         echo "Error: extract_cti_headers.sh failed for L4T $L4T_VERSION" >&2
         exit 1
      fi
   else
      # Always pass the CONFIGURED archive path, even when the file is absent.
      # The extractor derives the delta cache name from it, so handing it an
      # empty string instead would send it back to its own filename glob, which
      # can legitimately match a different archive in archives/CTI/ (e.g. one
      # renamed out of the way) and would then look for — and rebuild — a cache
      # under that other name. A path that does not exist is handled correctly:
      # the extractor falls back to the cache derived from it.
      update_status "Extracting CTI sources..."
      if ! "$ROOT_DIR/tools/extract_cti_sources.sh" "$L4T_VERSION" \
              "$CTI_ARCHIVE_DIR/$VENDOR_ARCHIVE" "$JETSON_DIR/$LINUX_FOR_TEGRA_DIR/source"; then
         echo "Error: extract_cti_sources.sh failed for L4T $L4T_VERSION" >&2
         exit 1
      fi
   fi
fi

# Mark this build tree as fully prepared: execution reached the end of the
# script without hitting one of its explicit `exit 1` paths (the vendor archive
# and extraction failures above all exit explicitly). Note this script does NOT
# use `set -e`, so this is "reached the end", not "every single command
# succeeded" — still far more accurate than .bsp_done, which is written early on
# and survives a run interrupted before the vendor extraction. Used on the next
# run to tell a genuinely fresh prepare from a re-run: see the vendor source
# layer cleanup at the top of this script.
touch "$JETSON_DIR/$LINUX_FOR_TEGRA_DIR/.prepare_done"

update_status "Done"
echo ""
echo "============================================"
echo "L4T ${L4T_VERSION_EXTENDED} environment prepared successfully"
echo "============================================"
echo ""
echo "Next steps:"
echo "  1. Copy Exosens sources:"
echo "     ./l4t_copy_sources.sh -v $L4T_VERSION${VENDOR:+ -V $VENDOR}${CARRIER_BOARD:+ -c $CARRIER_BOARD}"
echo "============================================"
