#!/usr/bin/env python3
"""
Phase 1 — Script-level integration tests for eg_dt_camera_config_set.sh.

The test matrix is generated by test/config/test_matrix.py from eg_config.yaml
(single source of truth). For each (version, platform_id) we iterate:
  - cameras × ports     → what the user might configure
  - extlinux_state      → starting state of /boot/extlinux/extlinux.conf
  - path_state          → optional: fdtget available / missing

Each test case runs the REAL script with REAL overlays (from the versioned
build output) and REAL base DTBs (including Auvidea X230D DTBs). Coverage
includes IMX219/IMX477 detection, 2-port base overlay selection, port >=2
rejection in 2-port mode, and graceful handling of missing tools.

Run inside Docker via test/integration/run_inside_container.sh.
"""
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from typing import Iterator

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT    = "/repo"
SCRIPT       = f"{REPO_ROOT}/sources/common/Linux_for_Tegra/rootfs/usr/bin/eg_dt_camera_config_set.sh"
VERIFY_DT    = f"{REPO_ROOT}/test/integration/verify_dt.py"
AUVIDEA_DIR  = f"{REPO_ROOT}/test/dts/auvidea"
EXTLINUX_TPL = f"{REPO_ROOT}/test/dts/extlinux"
BOOT_DIR     = "/boot"
PROC_DT      = "/tmp/fake_proc_dt"

sys.path.insert(0, f"{REPO_ROOT}/test/config")
from test_matrix import generate_matrix, Entry  # noqa: E402

# ---------------------------------------------------------------------------
# Camera mapping (mirrors script's CAMERA_LANES)
# ---------------------------------------------------------------------------
CAMERA_LANE_SUFFIX = {
    "Dione":        "",
    "MicroCube":    "ec-1-lane",
    "MicroCube640": "ec-1-lane",
    "SmartIR640":   "ec-2-lanes",
    "Crius1280":    "ec-2-lanes",
    "iLumos":       "ilumos",
    "Microlynx":    "microlynx",
}
CAMERA_LANE_NAME = {
    "MicroCube":    "EC_1_lane",
    "MicroCube640": "EC_1_lane",
    "SmartIR640":   "EC_2_lanes",
    "Crius1280":    "EC_2_lanes",
    "iLumos":       "iLumos",
    "Microlynx":    "Microlynx",
}
TEST_CAMERAS = list(CAMERA_LANE_SUFFIX.keys())

# ---------------------------------------------------------------------------
# Extlinux state templates
# ---------------------------------------------------------------------------
EXTLINUX_STATES = ["fresh", "previously_eg", "no_primary", "empty"]


def render_extlinux(state: str, fdt_path: str, previous_overlays: str = "") -> str | None:
    """Return extlinux.conf content for the given state, with {FDT} substituted.

    Returns None for 'empty' → caller should not create the file.
    """
    if state == "empty":
        return None
    tpl_path = f"{EXTLINUX_TPL}/{state}.conf"
    with open(tpl_path) as f:
        tpl = f.read()
    basename_no_ext = os.path.splitext(os.path.basename(fdt_path))[0]
    return (tpl
            .replace("{FDT}", fdt_path)
            .replace("{FDT_BASENAME_NO_EXT}", basename_no_ext)
            .replace("{PREVIOUS_OVERLAYS}", previous_overlays))


# ---------------------------------------------------------------------------
# /proc/device-tree simulation
# ---------------------------------------------------------------------------

def setup_proc_dt(entry: Entry, dtb_path: str, state: str) -> None:
    """Populate /tmp/fake_proc_dt from the base DTB (or from merged DTB if state=previously_eg).

    In state='previously_eg' we simulate that a previous install's user-custom.dtb is
    what's currently booted — the script should read /proc/device-tree and find NO
    rbpcv2_imx219 directories (because they were already disabled or removed), but the
    new code path reads the primary kernel DTB which DOES have them. The test verifies
    the script detects IMX219 in the base DTB and passes the disable arg.
    """
    shutil.rmtree(PROC_DT, ignore_errors=True)
    os.makedirs(PROC_DT, exist_ok=True)

    # compatible string (mock grep maps /proc/device-tree → PROC_DT)
    with open(f"{PROC_DT}/compatible", "w") as f:
        f.write(entry.compat)

    # In 'previously_eg' state, /proc reflects a merged user-custom DTB where IMX was
    # already disabled — so we intentionally create NO imx219 directories.
    if state == "previously_eg":
        return

    # Otherwise (fresh, no_primary): /proc reflects the base kernel DTB directly.
    r = subprocess.run(
        ["dtc", "-I", "dtb", "-O", "dts", dtb_path],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        return

    dts = r.stdout
    for pattern in ("rbpcv2_imx219", "rbpcv3_imx477"):
        for m in re.finditer(r"(" + pattern + r"[^\s{]*)\s*\{", dts):
            node_name = m.group(1)
            os.makedirs(f"{PROC_DT}/{node_name}", exist_ok=True)


# ---------------------------------------------------------------------------
# /boot population
# ---------------------------------------------------------------------------

def populate_boot_dtbos(entry: Entry) -> None:
    """Symlink every DTBO from the build output into /boot (one-time per entry).

    The script does `[[ -f /boot/<prefix>-cams-dione-2ports.dtbo ]]` for 2-port
    detection — the file must exist as a concrete /boot/*.dtbo entry.
    """
    for f in os.listdir(BOOT_DIR):
        if f.endswith(".dtbo"):
            try:
                os.remove(os.path.join(BOOT_DIR, f))
            except OSError:
                pass
    if os.path.isdir(entry.dtbo_boot_dir):
        for f in os.listdir(entry.dtbo_boot_dir):
            if f.endswith(".dtbo"):
                src = os.path.join(entry.dtbo_boot_dir, f)
                dst = os.path.join(BOOT_DIR, f)
                try:
                    os.symlink(src, dst)
                except OSError:
                    shutil.copy(src, dst)


def populate_boot(entry: Entry, state: str) -> None:
    """Reset per-test state in /boot (extlinux.conf + stale artefacts)."""
    shutil.rmtree(f"{BOOT_DIR}/extlinux", ignore_errors=True)
    os.makedirs(f"{BOOT_DIR}/extlinux", exist_ok=True)
    for f in ("kernel_merged.dtb", "cbh_calls.log"):
        p = f"{BOOT_DIR}/{f}"
        if os.path.exists(p):
            os.remove(p)
    content = render_extlinux(state, entry.base_dtb)
    if content is not None:
        with open(f"{BOOT_DIR}/extlinux/extlinux.conf", "w") as f:
            f.write(content)
    # 'empty' state: do not create the file at all


# ---------------------------------------------------------------------------
# Overlay map for the mock config-by-hardware.py
# ---------------------------------------------------------------------------

def build_overlay_map(entry: Entry) -> dict[str, str]:
    boot = entry.dtbo_boot_dir
    bpfx = entry.dtbo_base_prefix
    lpfx = entry.dtbo_lane_prefix
    ports = entry.ports
    is_forecr = entry.is_forecr

    m: dict[str, str] = {}

    # Base overlay
    base_key = "Exosens Cameras for DSBOARD-ORNXS" if is_forecr else "Exosens Cameras"
    base_dtbo = f"{boot}/{bpfx}-cams-dione.dtbo"
    if os.path.exists(base_dtbo):
        m[base_key] = base_dtbo

    # Global variant (tegra234 only)
    global_dtbo = f"{boot}/{bpfx}-cams-dione-global.dtbo"
    if os.path.exists(global_dtbo):
        m["Exosens Cameras (global)"] = global_dtbo

    # 2-port variant (35.1 AGX Orin concord only)
    twoports_dtbo = f"{boot}/{bpfx}-cams-dione-2ports.dtbo"
    if os.path.exists(twoports_dtbo):
        m["Exosens Cameras - 2 ports"] = twoports_dtbo

    # Disable overlays
    for imx in ("imx219", "imx477"):
        dtbo = f"{boot}/{bpfx}-cams-disable-{imx}.dtbo"
        if os.path.exists(dtbo):
            m[f"Exosens Cameras. Disable {imx}"] = dtbo

    # Per-port lane overlays
    lane_suffixes = {
        "ec-1-lane":  "EC_1_lane",
        "ec-2-lanes": "EC_2_lanes",
        "ilumos":     "iLumos",
        "microlynx":  "Microlynx",
    }
    for port in range(ports):
        for suffix, lane in lane_suffixes.items():
            dtbo = f"{boot}/{lpfx}-cam{port}-{suffix}.dtbo"
            if os.path.exists(dtbo):
                m[f"Exosens Cameras. CAM{port}:{lane}"] = dtbo

    return m


def write_overlays_file(overlay_map: dict[str, str], path: str) -> None:
    with open(path, "w") as f:
        f.write("Header 2: Jetson CSI Connector\n")
        f.write("  Available hardware modules:\n")
        for i, name in enumerate(overlay_map, 1):
            f.write(f"  {i}. {name}\n")


# ---------------------------------------------------------------------------
# Running the script
# ---------------------------------------------------------------------------

def run_script(entry: Entry, port: int, camera: str,
               overlay_map: dict[str, str], env_overrides: dict[str, str]) -> tuple[int, str, str]:
    cbh_log = f"{BOOT_DIR}/cbh_calls.log"
    overlays_file = f"{BOOT_DIR}/overlays.txt"
    write_overlays_file(overlay_map, overlays_file)

    env = os.environ.copy()
    env.update({
        "TEST_BOARD_SHORT":      entry.board_short,
        "TEST_CAMERA_PORTS":     str(entry.ports),
        "TEST_L4T_MODE":         entry.l4t_mode,
        "TEST_BASE_DTB":         entry.base_dtb,
        "TEST_BOOT_DIR":         BOOT_DIR,
        "TEST_OVERLAY_DTBO_JSON": json.dumps(overlay_map),
        "TEST_CBH_LOG":          cbh_log,
        "TEST_OVERLAYS_FILE":    overlays_file,
        "TEST_PROC_DT":          PROC_DT,
    })
    env.update(env_overrides)

    r = subprocess.run(
        ["bash", SCRIPT, f"{port}/{camera}"],
        env=env, capture_output=True, text=True,
    )
    return r.returncode, r.stdout, r.stderr


# ---------------------------------------------------------------------------
# Merged DTB retrieval (36.x) — apply fdtoverlay sequentially
# ---------------------------------------------------------------------------

def get_merged_dtb_36x() -> tuple[str | None, str]:
    extlinux = f"{BOOT_DIR}/extlinux/extlinux.conf"
    if not os.path.exists(extlinux):
        return None, "no extlinux.conf"

    content = open(extlinux).read()
    # Extract the JetsonIO block's FDT + OVERLAYS
    jio = re.search(r"LABEL JetsonIO(.+?)(?=^LABEL |\Z)", content, re.S | re.M)
    if not jio:
        return None, "no JetsonIO label"
    block = jio.group(1)
    fdt_m = re.search(r"^\s*FDT\s+(\S+)", block, re.M)
    ovl_m = re.search(r"^\s*OVERLAYS\s+(\S+)", block, re.M)
    if not fdt_m:
        return None, "no FDT in JetsonIO block"

    fdt = fdt_m.group(1)
    dtbos = ovl_m.group(1).split(",") if ovl_m else []

    current = fdt
    tmp_files = []
    for i, dtbo in enumerate(dtbos):
        out = tempfile.mktemp(suffix=f".{i}.dtb", dir="/tmp")
        r = subprocess.run(["fdtoverlay", "-i", current, "-o", out, dtbo],
                           capture_output=True, text=True)
        if r.returncode != 0:
            for f in tmp_files:
                try: os.remove(f)
                except OSError: pass
            return None, r.stderr.strip()
        if current != fdt:
            try: os.remove(current)
            except OSError: pass
        tmp_files.append(out)
        current = out

    return current, ""


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
RED    = "\033[0;31m"
GREEN  = "\033[0;32m"
YELLOW = "\033[1;33m"
CYAN   = "\033[0;36m"
BOLD   = "\033[1m"
NC     = "\033[0m"


def _pass(msg: str) -> None:  print(f"  {GREEN}PASS {NC} {msg}")
def _xfail(msg: str) -> None: print(f"  {GREEN}XFAIL{NC} {msg}")
def _xpass(msg: str) -> None: print(f"  {YELLOW}XPASS{NC} {msg}")
def _fail(msg: str) -> None:  print(f"  {RED}FAIL {NC} {msg}")
def _skip(msg: str) -> None:  print(f"  {YELLOW}SKIP {NC} {msg}")


# ---------------------------------------------------------------------------
# Expected outcomes — predict how the script SHOULD behave
# ---------------------------------------------------------------------------
# Outcome tags:
#   "pass"   — script exits 0 and behavior assertions hold
#   "xfail:<reason>" — script exits non-zero with a specific, expected reason
#     e.g. "xfail:port_rejected_in_2ports_mode"

def will_use_2ports(entry: Entry) -> bool:
    """True iff the script will switch base_devicetree to 'Exosens Cameras - 2 ports'.
    This happens only for Auvidea X230D on L4T 35.1 (kernel DTB lacks channel@2).
    """
    if entry.platform_id != "agx_orin_x230d" or entry.version != "35.1":
        return False
    # The 2-port DTBO must be in the build output (only 35.1 AGX concord builds it)
    twoports = f"{entry.dtbo_boot_dir}/{entry.dtbo_base_prefix}-cams-dione-2ports.dtbo"
    return os.path.exists(twoports)


def expected_outcome(entry: Entry, state: str, port: int, camera: str) -> tuple[str, str]:
    """Return (outcome, reason) for this combination.

    outcome ∈ {"pass", "xfail:<name>"}.
    """
    # ─── Boards where the kernel DTB lacks channel@2/@3 (Auvidea X230D on L4T 35.1)
    is_2port_board = (entry.platform_id == "agx_orin_x230d" and entry.version == "35.1")

    # 2-port mode requires the script to detect the limitation via LABEL primary
    # in extlinux.conf (the only reliable source). States without it cause the
    # script to fall back to the regular 4-port overlay which fails fdtoverlay
    # on the 2-channel kernel DTB. This is the documented behavior.
    if is_2port_board and state in ("empty", "no_primary"):
        return ("xfail:no_label_primary_2port_board",
                "extlinux.conf lacks LABEL primary → script cannot detect the "
                "2-channel kernel DTB → regular 4-port DTBO fails fdtoverlay")

    # 2-port mode detection succeeded, but port ≥ 2 is not exposed on the board.
    # Script rejects with explicit "port X not available" error.
    if will_use_2ports(entry) and state not in ("empty", "no_primary") and port >= 2:
        return ("xfail:port_rejected_in_2ports_mode",
                "no channel@2 in kernel DTB, script guards against port ≥ 2")

    return "pass", ""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

@dataclass
class Result:
    passed: int = 0
    xfailed: int = 0    # expected failure, occurred
    xpassed: int = 0    # expected failure, unexpectedly passed (warn)
    failed: int = 0
    skipped: int = 0
    failures: list = None


def assert_script_behavior(
    entry: Entry, state: str, port: int, camera: str,
    exit_code: int, stdout: str, stderr: str,
    overlay_map: dict,
) -> tuple[bool, str]:
    """Return (ok, detail_string). Checks behavior specific to the state dimension."""
    combined = stdout + stderr
    cbh_log_path = f"{BOOT_DIR}/cbh_calls.log"
    cbh_line = open(cbh_log_path).read().strip() if os.path.exists(cbh_log_path) else ""

    # 1. Exit code should be 0 unless the test case legitimately expects failure
    if exit_code != 0:
        return False, f"exit={exit_code} — {combined.splitlines()[:3]}"

    # 2. CBH log should contain the expected base overlay for this entry.
    is_tegra234 = entry.compat == "nvidia,tegra234"

    # 2-port detection scenario: Auvidea 35.1 AGX Orin base DTB has no channel@2, and
    # the 2-port DTBO is built for 35.1 — script MUST switch base to "2 ports".
    in_2ports = (
        entry.platform_id == "agx_orin_x230d"
        and entry.version == "35.1"
        and "Exosens Cameras - 2 ports" in overlay_map
        and state != "empty"              # extlinux.conf required to read primary DTB
    )
    if in_2ports:
        if "Exosens Cameras - 2 ports" not in cbh_line:
            return False, f"expected 'Exosens Cameras - 2 ports' in CBH args, got: {cbh_line}"
    # Forecr boards: base must be "Exosens Cameras for DSBOARD-ORNXS"
    elif entry.is_forecr:
        if "Exosens Cameras for DSBOARD-ORNXS" not in cbh_line:
            return False, f"expected Forecr base overlay, got: {cbh_line}"
    # t234 non-Forecr, Dione-only, no active IMX → script upgrades to "(global)".
    # Per-port cams (camera != Dione) keep the per-channel "Exosens Cameras" base
    # because per-port DTBOs target endpoint@0, incompatible with the global base's
    # endpoint@2 numbering. See eg_dt_camera_config_set.sh global-upgrade block.
    imx219_expected = _imx219_expected_in_base(entry)
    if (is_tegra234
            and not entry.is_forecr
            and not in_2ports
            and camera == "Dione"
            and imx219_expected == 0
            and "Exosens Cameras (global)" in overlay_map):
        if "Exosens Cameras (global)" not in cbh_line:
            return False, f"expected (global) upgrade for Dione-only, got: {cbh_line}"
    elif (is_tegra234
            and not entry.is_forecr
            and not in_2ports
            and camera != "Dione"
            and "Exosens Cameras (global)" in overlay_map):
        # Must NOT upgrade to global when per-port cam is configured
        if "Exosens Cameras (global)" in cbh_line:
            return False, (f"incorrect (global) upgrade with per-port cam "
                           f"'{camera}': {cbh_line}")

    # 3. IMX219 disable arg: when the base kernel DTB has active IMX219 AND the
    #    separate disable overlay is built for this platform, CBH must receive
    #    the arg. Exception: in 2-port mode the 2ports.dtbo already folds the
    #    disable into its own fragments (the disable DTBO targets cam2/cam3
    #    paths that don't exist on 2-channel kernel DTBs), so the script
    #    intentionally skips the arg.
    has_disable = "Exosens Cameras. Disable imx219" in overlay_map
    if imx219_expected and has_disable and not in_2ports:
        if "Exosens Cameras. Disable imx219" not in cbh_line:
            return False, (f"expected disable imx219 (state={state}, "
                           f"base has {imx219_expected} active), CBH: {cbh_line}")
    elif imx219_expected and in_2ports:
        # Conversely, we MUST NOT send the 4-port disable DTBO in 2-port mode
        if "Exosens Cameras. Disable imx219" in cbh_line:
            return False, (f"disable imx219 arg leaked in 2-port mode: {cbh_line}")

    return True, f"state={state}, base={_base_from_cbh(cbh_line)}"


def _imx219_expected_in_base(entry: Entry) -> int:
    """Count of active rbpcv2_imx219 nodes in the base DTB."""
    r = subprocess.run(["dtc", "-I", "dtb", "-O", "dts", entry.base_dtb],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return 0
    dts = r.stdout
    count = 0
    for m in re.finditer(r"rbpcv2_imx219[^{;\n]*\{", dts):
        open_pos = m.end() - 1
        depth = 0
        i = open_pos
        disabled = False
        while i < len(dts):
            c = dts[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    break
            elif depth == 1 and dts[i:i + 6] == "status":
                nl = dts.find("\n", i)
                if '"disabled"' in dts[i:nl] if nl != -1 else dts[i:]:
                    disabled = True
            i += 1
        if not disabled:
            count += 1
    return count


def _base_from_cbh(line: str) -> str:
    m = re.search(r"Exosens Cameras[^|]*", line)
    return (m.group(0).strip() if m else "?")[:40]


def _run_one(entry: Entry, state: str, port: int, camera: str,
             overlay_map: dict, result: Result) -> None:
    """Run a single test case, update result counters."""
    label = f"{entry.version}/{entry.platform_id}/{state}/{camera}/port{port}"

    expected, reason = expected_outcome(entry, state, port, camera)

    populate_boot(entry, state)
    setup_proc_dt(entry, entry.base_dtb, state)

    rc, out, err = run_script(entry, port, camera, overlay_map, env_overrides={})

    if expected == "pass":
        if rc == 0:
            ok, detail = assert_script_behavior(entry, state, port, camera,
                                               rc, out, err, overlay_map)
            if ok:
                _pass(f"{label}: {detail}")
                result.passed += 1
            else:
                _fail(f"{label}: {detail}")
                result.failed += 1
                result.failures.append(label)
        else:
            snippet = (err or out).strip().splitlines()[-3:]
            _fail(f"{label}: unexpected rc={rc}: {snippet}")
            result.failed += 1
            result.failures.append(label)
    else:  # expected starts with "xfail:"
        tag = expected.split(":", 1)[1]
        if rc != 0:
            _xfail(f"{label}: xfail({tag}) rc={rc} — {reason}")
            result.xfailed += 1
        else:
            _xpass(f"{label}: unexpected pass where xfail({tag}) expected — {reason}")
            result.xpassed += 1


def run_provoked_failures(entry: Entry, overlay_map: dict, result: Result) -> None:
    """Boundary + negative-path tests.

    For every platform × L4T version, we run a battery of inputs that the script
    MUST reject. Each case asserts rc != 0 AND that the output contains a
    telltale substring — so a silent exit on a different error is flagged.

    The cases cover: argument shape, port parsing, port range, camera name
    canonicalisation, empty fields, and multi-arg mixed validity. Many of these
    would silently misbehave if the script's arg loop were later simplified.
    """
    populate_boot(entry, "fresh")
    setup_proc_dt(entry, entry.base_dtb, "fresh")

    p_beyond = entry.ports          # first out-of-range port (ports-1 is max valid)
    p_far    = entry.ports + 42

    # (description, args, needle, applies_condition)
    # `applies_condition` allows per-entry disabling when the case isn't meaningful
    cases: list[tuple[str, list[str], str, bool]] = [
        # ─── Argument shape ──────────────────────────────────────────────────
        ("bad_arg_format_noslash",  ["noslash"],            "invalid argument",  True),
        ("bad_arg_multi_valid_bad", ["0/Dione", "noslash"], "invalid argument",  True),
        # ─── Port parsing ────────────────────────────────────────────────────
        ("port_non_numeric",        ["zero/Dione"],         "invalid port",      True),
        ("port_negative",           ["-1/Dione"],           "invalid port",      True),
        ("port_hex",                ["0x1/Dione"],          "invalid port",      True),
        ("port_empty",              ["/Dione"],             "invalid port",      True),
        # ─── Port range (boundary: exactly ports, then well above) ───────────
        ("port_boundary_just_over", [f"{p_beyond}/Dione"],  "invalid port",      True),
        ("port_far_overflow",       [f"{p_far}/Dione"],     "invalid port",      True),
        # ─── Camera validation ───────────────────────────────────────────────
        ("camera_unknown_typo",     ["0/Dion"],             "unknown camera",    True),
        ("camera_unknown_bogus",    ["0/BogusCam"],         "unknown camera",    True),
        ("camera_wrong_case",       ["0/DIONE"],            "unknown camera",    True),
        ("camera_empty",            ["0/"],                 "unknown camera",    True),
    ]

    # Some cases overlap with the 2-port-mode code path and are already covered
    # by the main matrix's XFAIL assertion, but running them as provoked cases
    # too verifies the script emits the SAME error consistently.

    for desc, args, needle, applies in cases:
        if not applies:
            continue
        label = f"{entry.version}/{entry.platform_id}/provoke/{desc}"
        cbh_log = f"{BOOT_DIR}/cbh_calls.log"
        overlays_file = f"{BOOT_DIR}/overlays.txt"
        write_overlays_file(overlay_map, overlays_file)
        env = os.environ.copy()
        env.update({
            "TEST_BOARD_SHORT":       entry.board_short,
            "TEST_CAMERA_PORTS":      str(entry.ports),
            "TEST_L4T_MODE":          entry.l4t_mode,
            "TEST_BASE_DTB":          entry.base_dtb,
            "TEST_BOOT_DIR":          BOOT_DIR,
            "TEST_OVERLAY_DTBO_JSON": json.dumps(overlay_map),
            "TEST_CBH_LOG":           cbh_log,
            "TEST_OVERLAYS_FILE":     overlays_file,
            "TEST_PROC_DT":           PROC_DT,
        })
        r = subprocess.run(["bash", SCRIPT] + args, env=env,
                           capture_output=True, text=True)
        combined = (r.stdout + r.stderr).lower()

        if r.returncode != 0 and needle in combined:
            _xfail(f"{label}: rejected rc={r.returncode} (matches '{needle}')")
            result.xfailed += 1
        else:
            _fail(f"{label}: rc={r.returncode} but did not reject with '{needle}' "
                  f"(output: {(r.stdout+r.stderr)[:160]!r})")
            result.failed += 1
            result.failures.append(label)


def main() -> int:
    result = Result(failures=[])
    entries = list(generate_matrix())
    if not entries:
        print("ERROR: empty test matrix (eg_config.yaml or hardware.yaml broken?)")
        return 2

    for entry in entries:
        # Strict prerequisite: base DTB and base DTBO must exist. Failure here means
        # a broken build — not a valid skip. We record a FAIL (not a SKIP) so the
        # signal reaches CI.
        if not os.path.exists(entry.base_dtb):
            _fail(f"L4T {entry.version} / {entry.platform_id}: base DTB missing at "
                  f"{entry.base_dtb} — build output incomplete")
            result.failed += 1
            result.failures.append(f"{entry.version}/{entry.platform_id}/prereq_base_dtb")
            continue

        overlay_map = build_overlay_map(entry)
        base_key = ("Exosens Cameras for DSBOARD-ORNXS"
                    if entry.is_forecr else "Exosens Cameras")
        if base_key not in overlay_map:
            _fail(f"L4T {entry.version} / {entry.platform_id}: base DTBO {base_key!r} "
                  f"missing in {entry.dtbo_boot_dir} — build output incomplete")
            result.failed += 1
            result.failures.append(f"{entry.version}/{entry.platform_id}/prereq_base_dtbo")
            continue

        header = (f"{BOLD}{CYAN}━━━ L4T {entry.version} / {entry.platform_id} "
                  f"/ {entry.board_short} / {entry.l4t_mode} ━━━{NC}")
        print(f"\n{header}")

        # DTBOs are static per entry — copy once
        populate_boot_dtbos(entry)

        # Main matrix: (state, port, camera)
        for state in EXTLINUX_STATES:
            for port in range(entry.ports):
                for camera in TEST_CAMERAS:
                    suffix = CAMERA_LANE_SUFFIX[camera]
                    if suffix:
                        name = CAMERA_LANE_NAME[camera]
                        if f"Exosens Cameras. CAM{port}:{name}" not in overlay_map:
                            # Not a silent skip — tell the user why we're skipping.
                            # This combo is legitimately impossible (DTBO not built for
                            # this port on this platform) so we don't run a test.
                            _skip(f"{entry.version}/{entry.platform_id}/{state}/"
                                  f"{camera}/port{port}: no DTBO "
                                  f"'{entry.dtbo_lane_prefix}-cam{port}-{suffix}.dtbo'")
                            result.skipped += 1
                            continue
                    _run_one(entry, state, port, camera, overlay_map, result)

        # Provoked failures (negative tests) — always run one set per entry
        run_provoked_failures(entry, overlay_map, result)

    print()
    print(f"{BOLD}Results:{NC}  "
          f"{GREEN}{result.passed} pass{NC}  "
          f"{GREEN}{result.xfailed} xfail{NC}  "
          f"{YELLOW}{result.xpassed} xpass{NC}  "
          f"{RED}{result.failed} fail{NC}  "
          f"{YELLOW}{result.skipped} skip{NC}")

    if result.failures:
        print(f"\n{BOLD}Failed:{NC}")
        for f in result.failures[:40]:
            print(f"  - {f}")
        if len(result.failures) > 40:
            print(f"  ... and {len(result.failures) - 40} more")

    # xpass is a warning, not a failure (the thing we thought was broken now works —
    # someone should update the xfail list). Real failures still dominate the exit code.
    return 1 if result.failed else 0


if __name__ == "__main__":
    sys.exit(main())
